# Stage 1 - Build Stage
FROM node:14-alpine as builder

WORKDIR /app

COPY ./frontend-app .

RUN npm install --production

RUN npm run build

# Stage 2 - Final Stage
FROM nginx:1.21.6-alpine
ARG APP_PORT

RUN rm -rf /etc/nginx/conf.d

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build .
COPY --from=builder /app/config/nginx /etc/nginx

EXPOSE $APP_PORT
CMD ["nginx", "-g", "daemon off;"]